### ISSUE TITLE
大佬……您这文件不全啊……

### ISSUE THREAD

**Issue by TaoRone** [youshandefeiyang/sub-web-config-backend#1]
还是说剩下的需要用原版后端么

**Comment by youshandefeiyang** [comment]
没问题啊，哪里不全了。。。

**Comment by TaoRone** [comment]
> 没问题啊，哪里不全了。。。

不好意思，前面没看懂，现在看懂了……文件很全……原来要搭配大佬的前端文件使用……

另外请问大佬，您这个后端的功能我是这样理解的，不知道对不对……
1、使用大佬前端后，通过大佬的后端地址（api.v1.mk）进行转换
2、将转换的链接上传到自建的托管后端

但现在有个问题……我生成链接可以，但是并没有成功上传到自己的托管后端

**Comment by TaoRone** [comment]
大佬我发现是默认将上传隐藏掉了……先谢谢您不留记录，但我这边在生成订阅链接中绑定了上传事件后，依旧没有执行……请问怎么解决啊。。。。

```  <el-button
                  style="width: 120px"
                  type="danger"
                  @click="makeUrl();confirmUploadConfig()"
                  :disabled="form.sourceSubUrl.length === 0"
                >生成订阅链接</el-button>```

**Comment by TaoRone** [comment]
> 大佬我发现是默认将上传隐藏掉了……先谢谢您不留记录，但我这边在生成订阅链接中绑定了上传事件后，依旧没有执行……请问怎么解决啊。。。。
> ``` <el-button
>                   style="width: 120px"
>                   type="danger"
>                   @click="makeUrl();confirmUploadConfig()"
>                   :disabled="form.sourceSubUrl.length === 0"
>                 >生成订阅链接</el-button>```
> ```

**Comment by TaoRone** [comment]
> > 大佬我发现是默认将上传隐藏掉了……先谢谢您不留记录，但我这边在生成订阅链接中绑定了上传事件后，依旧没有执行……请问怎么解决啊。。。。
> > ```                <el-button  style="width: 120px"
> >                   type="danger"
> >                   @click="makeUrl();confirmUploadConfig()"
> >                   :disabled="form.sourceSubUrl.length === 0"
> >                 >生成订阅链接</el-button>```
> > ```

**Comment by youshandefeiyang** [comment]
你自己搭建托管文本配置后端，需要自行在subconverter.vue中修改后端的默认链接，我readme中说的挺清楚了

**Comment by TaoRone** [comment]
> 你自己搭建托管文本配置后端，需要自行在subconverter.vue中修改后端的默认链接，我readme中说的挺清楚了

好吧。。。打扰大佬了，谢谢您，我再折腾试试
